$axure.loadCurrentPage({
  "url":"home_log_in.html",
  "generationDate":new Date(1403539909605.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f1e39e85f1e41ee8018944bee2aa697",
    "type":"Axure:Page",
    "name":"Home log in",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"10c1a6bcb66a40458a9124649804cdc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1280,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df16ec0d1a9042f6a05c2940976bd76c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1280,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u0.jpg"}},
{
          "id":"e6a68d63324b4e4fa075c29ebe9a1d89",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb2e078b2f074854baea4c6b152f664f"},
{
          "id":"4bdd16ce36194f829c4a214718a8e34f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1114,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6cef136aecb418b958d8d0fb24725dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1114,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u12.png",
            "mouseOver~":"images/home_new/u12_mouseOver.png"}},
{
          "id":"52f860b258f34cf4b565f2e5bd37e44e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1020,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcdeb8daffdc471bb49d6307229a42b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1020,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u12.png",
            "mouseOver~":"images/home_new/u12_mouseOver.png"}},
{
          "id":"30c930ae71f14564af0d0ce068b8e36e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":927,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11086290b6f5480398f996cf1c16ee22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":927,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u12.png",
            "mouseOver~":"images/home_new/u12_mouseOver.png"}},
{
          "id":"602aaabc14274c4fbc34df3f3f363284",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":833,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cebcd60c861b47aabdd41efd14506559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":833,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u12.png",
            "mouseOver~":"images/home_new/u12_mouseOver.png"}},
{
          "id":"8699471356844769ab1299f1c165e12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":739,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6376accd227849d7922ade5c045ca8e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":739,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u12.png",
            "mouseOver~":"images/home_new/u12_mouseOver.png"}},
{
          "id":"648a137ee4a2431a88c296adce9ad929",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":570,
              "y":330},
            "size":{
              "width":81,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bdaa3a50ea14d9c98afbfef282d850d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":330},
                "size":{
                  "width":81,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video_in in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_in.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u22.png"}},
{
          "id":"7985cb4b81134056a57ca5bbc7c92a16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":230,
              "y":335},
            "size":{
              "width":60,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f23504ca3024b20b17cd59fbbbdb5ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":335},
                "size":{
                  "width":60,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video_in in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_in.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u22.png"}},
{
          "id":"fc7e400590bf46f7b5c702f42a2c4cdd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":689,
              "y":470},
            "size":{
              "width":55,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8495b0648c664a88a812eb85e87e533b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":689,
                  "y":470},
                "size":{
                  "width":55,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video_in in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_in.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u22.png"}},
{
          "id":"a361bc9fcbfd4f4cbaec9741460b1748",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":744,
              "y":210},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b22bdfa8174e569e1e48e4c0180efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":210},
                "size":{
                  "width":66,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video_in in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_in.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u22.png"}},
{
          "id":"c77e1ff612b04142ad5af847c890f287",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":169,
              "y":408},
            "size":{
              "width":71,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e348a3f23d0b43c0a58b62797b056776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":408},
                "size":{
                  "width":71,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video_in in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_in.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u22.png"}},
{
          "id":"ace2022b1d494b749a4e4d44dff9a131",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d621f7e60430446f9e8699f46216c640"}]}},
  "masters":{
    "bb2e078b2f074854baea4c6b152f664f":{
      "packageId":"bb2e078b2f074854baea4c6b152f664f",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43908beeeec1483d8cb2df8f5eaa2e43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":920},
              "size":{
                "width":1280,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cde370c93f50410087af9b49ff4d8b76",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":920},
                  "size":{
                    "width":1280,
                    "height":40}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"016b41db8d9547b6b3f8b61591c69297",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"085d5ab409334489bb6c9f0828f02c66",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"cc1a8431622b4110ad80a2438401755b",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"images/home_new/u3.png"}},
{
            "id":"03de8ddf973d4e64ad21713129ad31fd",
            "label":"facebook icone",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":880,
                "y":924},
              "size":{
                "width":30,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f54a7aeb5d5540a18f733d6bbc3b6f81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":880,
                    "y":924},
                  "size":{
                    "width":30,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open https://www.facebook.com/warpathcommunity?ref=hl in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"https://www.facebook.com/warpathcommunity?ref=hl",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/facebook_icone_u8.png"}},
{
            "id":"1044fc2ff3784bcb91ae7c0270b5e1f8",
            "label":"instagram icon",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":950,
                "y":926},
              "size":{
                "width":30,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"749bfa03b93a4b6b8eec17b252f0a62d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":950,
                    "y":926},
                  "size":{
                    "width":30,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open http://instagram.com/warpathcommunity in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://instagram.com/warpathcommunity",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/instagram_icon_u10.png"}}]}},
    "d621f7e60430446f9e8699f46216c640":{
      "packageId":"d621f7e60430446f9e8699f46216c640",
      "type":"Axure:Master",
      "name":"Header log in",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9f139b2fe90d4dbead3502df555a174d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF797979},
              "size":{
                "width":1280,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f79033071740f9b103569baf4c06df",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF797979},
                  "size":{
                    "width":1280,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_new/u39.png"}},
{
            "id":"7f33424607814793b58b3d78593beb0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":0},
              "size":{
                "width":130,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5decc54edae450e8eb4d9306695250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":0},
                  "size":{
                    "width":130,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u41.png"}},
{
            "id":"2c3165e200cd4fe88e47b360a7918266",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":91,
                "y":5},
              "size":{
                "width":108,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed083319a04d42abb62d4b13896cf78c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":91,
                    "y":5},
                  "size":{
                    "width":108,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u43.png"}},
{
            "id":"251c5d36672949c7b39959cf90137238",
            "label":"Type de recherche",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":281,
                "y":16},
              "size":{
                "width":70,
                "height":29}},
            "adaptiveStyles":{
}},
{
            "id":"a4d965d59f1449c79baf728c6e64e0bb",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":351,
                "y":16},
              "size":{
                "width":492,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onTextChange":{
                "description":"OnTextChange",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"Set text on focused widget equal to &quot;&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetFocusedWidgetText",
                              "arguments":[null,
{
                                  "exprType":"stringLiteral",
                                  "value":"",
                                  "stos":[]}]}]}}]}]}}},
{
            "id":"75817ca8ea724b21bf3ce8b73acc6b62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "fill":{
                "fillType":"solid",
                "color":0xFF434343},
              "location":{
                "x":843,
                "y":16},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e5acd9020a64e2dabc7477ac46888e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF434343},
                  "location":{
                    "x":843,
                    "y":16},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Page résultats in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"page_resultats.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u47.png",
              "mouseOver~":"images/home_new/u47_mouseOver.png"}},
{
            "id":"bf5e8c8074b04301a6d6f9c865f853f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":1035,
                "y":17},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9113f53a7cf41088451446e198b69d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":1035,
                    "y":17},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u49.png",
              "mouseOver~":"images/home_new/u49_mouseOver.png"}},
{
            "id":"dd2a7776e5144247913a3687db7b939f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":915,
                "y":17},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33e7a1229c9f4152b8f5be596f7cd800",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":915,
                    "y":17},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Monprofil_in in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"monprofil_in.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u49.png",
              "mouseOver~":"images/home_new/u49_mouseOver.png"}}]}}},
  "objectPaths":{
    "10c1a6bcb66a40458a9124649804cdc7":{
      "scriptId":"u0"},
    "df16ec0d1a9042f6a05c2940976bd76c":{
      "scriptId":"u1"},
    "e6a68d63324b4e4fa075c29ebe9a1d89":{
      "scriptId":"u2",
      "43908beeeec1483d8cb2df8f5eaa2e43":{
        "scriptId":"u3"},
      "cde370c93f50410087af9b49ff4d8b76":{
        "scriptId":"u4"},
      "016b41db8d9547b6b3f8b61591c69297":{
        "scriptId":"u5"},
      "085d5ab409334489bb6c9f0828f02c66":{
        "scriptId":"u6"},
      "cc1a8431622b4110ad80a2438401755b":{
        "scriptId":"u7"},
      "03de8ddf973d4e64ad21713129ad31fd":{
        "scriptId":"u8"},
      "f54a7aeb5d5540a18f733d6bbc3b6f81":{
        "scriptId":"u9"},
      "1044fc2ff3784bcb91ae7c0270b5e1f8":{
        "scriptId":"u10"},
      "749bfa03b93a4b6b8eec17b252f0a62d":{
        "scriptId":"u11"}},
    "4bdd16ce36194f829c4a214718a8e34f":{
      "scriptId":"u12"},
    "a6cef136aecb418b958d8d0fb24725dd":{
      "scriptId":"u13"},
    "52f860b258f34cf4b565f2e5bd37e44e":{
      "scriptId":"u14"},
    "bcdeb8daffdc471bb49d6307229a42b0":{
      "scriptId":"u15"},
    "30c930ae71f14564af0d0ce068b8e36e":{
      "scriptId":"u16"},
    "11086290b6f5480398f996cf1c16ee22":{
      "scriptId":"u17"},
    "602aaabc14274c4fbc34df3f3f363284":{
      "scriptId":"u18"},
    "cebcd60c861b47aabdd41efd14506559":{
      "scriptId":"u19"},
    "8699471356844769ab1299f1c165e12a":{
      "scriptId":"u20"},
    "6376accd227849d7922ade5c045ca8e7":{
      "scriptId":"u21"},
    "648a137ee4a2431a88c296adce9ad929":{
      "scriptId":"u22"},
    "3bdaa3a50ea14d9c98afbfef282d850d":{
      "scriptId":"u23"},
    "7985cb4b81134056a57ca5bbc7c92a16":{
      "scriptId":"u24"},
    "0f23504ca3024b20b17cd59fbbbdb5ed":{
      "scriptId":"u25"},
    "fc7e400590bf46f7b5c702f42a2c4cdd":{
      "scriptId":"u26"},
    "8495b0648c664a88a812eb85e87e533b":{
      "scriptId":"u27"},
    "a361bc9fcbfd4f4cbaec9741460b1748":{
      "scriptId":"u28"},
    "d5b22bdfa8174e569e1e48e4c0180efa":{
      "scriptId":"u29"},
    "c77e1ff612b04142ad5af847c890f287":{
      "scriptId":"u30"},
    "e348a3f23d0b43c0a58b62797b056776":{
      "scriptId":"u31"},
    "ace2022b1d494b749a4e4d44dff9a131":{
      "scriptId":"u32",
      "9f139b2fe90d4dbead3502df555a174d":{
        "scriptId":"u33"},
      "67f79033071740f9b103569baf4c06df":{
        "scriptId":"u34"},
      "7f33424607814793b58b3d78593beb0f":{
        "scriptId":"u35"},
      "c5decc54edae450e8eb4d9306695250d":{
        "scriptId":"u36"},
      "2c3165e200cd4fe88e47b360a7918266":{
        "scriptId":"u37"},
      "ed083319a04d42abb62d4b13896cf78c":{
        "scriptId":"u38"},
      "251c5d36672949c7b39959cf90137238":{
        "scriptId":"u39"},
      "a4d965d59f1449c79baf728c6e64e0bb":{
        "scriptId":"u40"},
      "75817ca8ea724b21bf3ce8b73acc6b62":{
        "scriptId":"u41"},
      "6e5acd9020a64e2dabc7477ac46888e2":{
        "scriptId":"u42"},
      "bf5e8c8074b04301a6d6f9c865f853f2":{
        "scriptId":"u43"},
      "c9113f53a7cf41088451446e198b69d4":{
        "scriptId":"u44"},
      "dd2a7776e5144247913a3687db7b939f":{
        "scriptId":"u45"},
      "33e7a1229c9f4152b8f5be596f7cd800":{
        "scriptId":"u46"}}}});