$axure.loadCurrentPage({
  "url":"home_step2.html",
  "generationDate":new Date(1403793406712.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b7ad75c7d3bb495e8ef2b1e9c42c0d27",
    "type":"Axure:Page",
    "name":"Home_step2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e6e937c3d80e40ed8c0ea3df7afbdaf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1280,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50424e4eb9d94997bf0f9bed24abb659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1280,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u0.jpg"}},
{
          "id":"ed5877d01e0a4ec4b04f12b703b32ad7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1046,
              "y":80},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3e4782ee576413c81c6a2d2c2ec3f51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1046,
                  "y":80},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u55.jpg"}},
{
          "id":"95b584391fd8407ead95313fe7dfc007",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1114,
              "y":80},
            "size":{
              "width":33,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c82215404d54d6aba904ff30a8c6e18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1114,
                  "y":80},
                "size":{
                  "width":33,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u57.png"}},
{
          "id":"b6dee754254c468ab869365be64c1f9a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb2e078b2f074854baea4c6b152f664f"},
{
          "id":"864208ae0ac24ee38e5cb7685b65625c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":570,
              "y":330},
            "size":{
              "width":81,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9f0701f5f04af68d566c066c18bd44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":330},
                "size":{
                  "width":81,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"ad9b1fbdd5b541719ff7df56153d5567",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":230,
              "y":335},
            "size":{
              "width":60,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d740f49946184314bfd4486bac5d1fc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":335},
                "size":{
                  "width":60,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"6a2811cf29d844bc8b34c43e4ac55a53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":689,
              "y":470},
            "size":{
              "width":55,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4aa3749c9145338657e94c8045c6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":689,
                  "y":470},
                "size":{
                  "width":55,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"f75e37dbff0f45209b8664d8974758bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":744,
              "y":210},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9462db1c6b72461ea8e2be8388fdb032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":210},
                "size":{
                  "width":66,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"6e932f1a021149749afe5dce5bd35567",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":169,
              "y":408},
            "size":{
              "width":71,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9219675ae47a40b89c19637278f38975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":408},
                "size":{
                  "width":71,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"a379361c0ad6458c801c39f1c2043af9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1114,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a66b6d03db974b9f830620391c6bb77a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1114,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"d6b85feadd494a5d937bde5712e197ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1020,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0269ec1e7961486d974f691ac3a65417",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1020,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"1539e9e0165a477996c07bbcaadd03f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":927,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7998d360627b4c6f8cea4fea658d9fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":927,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"8fa622a4ae954a67a125d8dad0192f4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":833,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cab58d60f64573b89c8b9dd759aed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":833,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"08c8b6d988054c028a58931e11a623ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":739,
              "y":610},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80b6f556bb4f4de2b56ce32cf541956f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":739,
                  "y":610},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"475f4f8280584d00bf8fd5433984da98",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"08c5e6d3e5f54a259a8534ebaa863b4a"},
{
          "id":"ac3cc2b6f8de438ab0aafafad5e93cbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x9ECCCCCC},
            "size":{
              "width":1280,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cedaa5cf448a403fb6f95904d78f1244",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x9ECCCCCC},
                "size":{
                  "width":1280,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u59.png"}},
{
          "id":"74711a60c8374d6a963005047d6848e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":179},
            "size":{
              "width":600,
              "height":326},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04186d64be524a2699cb784f99f7000e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":179},
                "size":{
                  "width":600,
                  "height":326},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step2/u71.png"}},
{
          "id":"2288d8da4b7348828b9616573c98cfae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":74},
            "size":{
              "width":270,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aefbf27d8557497080bab8f48730f801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":74},
                "size":{
                  "width":270,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u61.png"}},
{
          "id":"0340e80b96034737a2493f50dda066d4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":468,
              "y":148},
            "size":{
              "width":28,
              "height":21},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d853d6d7a94df19b68b89320406782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":468,
                  "y":148},
                "size":{
                  "width":28,
                  "height":21},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u63.png"}},
{
          "id":"3a5542134515466e8f04a4b371b50a2e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Helvetica'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":439,
              "y":96},
            "size":{
              "width":21,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a6e3f7c2a3841829622447930cbe9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":439,
                  "y":96},
                "size":{
                  "width":21,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_step1/u65.png"}},
{
          "id":"5991d44cf30d4ce39b9541b3a02cb95b",
          "label":"BasicButton-Success",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "lineSpacing":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "opacity":"0.8"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF21CA6B},
            "location":{
              "x":600,
              "y":110},
            "size":{
              "width":90,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4805a218624cd194bb10d94a0da8aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "lineSpacing":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2,
                      "opacity":1},
                    "opacity":"0.8"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF21CA6B},
                "location":{
                  "x":600,
                  "y":110},
                "size":{
                  "width":90,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home_step3 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home_step3.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_step1/basicbutton-success_u79.png",
            "mouseOver~":"images/home_step1/basicbutton-success_u79.png"}},
{
          "id":"d6e5f971b0d245a481035b7a87b9c66d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":96},
            "size":{
              "width":120,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b74dbaaf6af34979bf2d7333faaf2ec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":96},
                "size":{
                  "width":120,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "bb2e078b2f074854baea4c6b152f664f":{
      "packageId":"bb2e078b2f074854baea4c6b152f664f",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43908beeeec1483d8cb2df8f5eaa2e43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":920},
              "size":{
                "width":1280,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cde370c93f50410087af9b49ff4d8b76",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":920},
                  "size":{
                    "width":1280,
                    "height":40}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"016b41db8d9547b6b3f8b61591c69297",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"085d5ab409334489bb6c9f0828f02c66",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"cc1a8431622b4110ad80a2438401755b",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"images/home_new/u3.png"}},
{
            "id":"03de8ddf973d4e64ad21713129ad31fd",
            "label":"facebook icone",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":880,
                "y":924},
              "size":{
                "width":30,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f54a7aeb5d5540a18f733d6bbc3b6f81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":880,
                    "y":924},
                  "size":{
                    "width":30,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open https://www.facebook.com/warpathcommunity?ref=hl in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"https://www.facebook.com/warpathcommunity?ref=hl",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/facebook_icone_u8.png"}},
{
            "id":"1044fc2ff3784bcb91ae7c0270b5e1f8",
            "label":"instagram icon",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":950,
                "y":926},
              "size":{
                "width":30,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"749bfa03b93a4b6b8eec17b252f0a62d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":950,
                    "y":926},
                  "size":{
                    "width":30,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open http://instagram.com/warpathcommunity in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://instagram.com/warpathcommunity",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/instagram_icon_u10.png"}}]}},
    "08c5e6d3e5f54a259a8534ebaa863b4a":{
      "packageId":"08c5e6d3e5f54a259a8534ebaa863b4a",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9f139b2fe90d4dbead3502df555a174d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF797979},
              "size":{
                "width":1280,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f79033071740f9b103569baf4c06df",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF797979},
                  "size":{
                    "width":1280,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_new/u43.png"}},
{
            "id":"7f33424607814793b58b3d78593beb0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":0},
              "size":{
                "width":130,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5decc54edae450e8eb4d9306695250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":0},
                  "size":{
                    "width":130,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u45.png"}},
{
            "id":"2c3165e200cd4fe88e47b360a7918266",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":91,
                "y":5},
              "size":{
                "width":108,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed083319a04d42abb62d4b13896cf78c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":91,
                    "y":5},
                  "size":{
                    "width":108,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u47.png"}},
{
            "id":"a4d965d59f1449c79baf728c6e64e0bb",
            "label":"search bar",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":258,
                "y":16},
              "size":{
                "width":492,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onTextChange":{
                "description":"OnTextChange",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"Set text on search bar equal to &quot;&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetWidgetFormText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["a4d965d59f1449c79baf728c6e64e0bb"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"",
                                  "stos":[]}]}]}}]}]}}},
{
            "id":"75817ca8ea724b21bf3ce8b73acc6b62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "fill":{
                "fillType":"solid",
                "color":0xFF434343},
              "location":{
                "x":820,
                "y":16},
              "size":{
                "width":70,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e5acd9020a64e2dabc7477ac46888e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF434343},
                  "location":{
                    "x":820,
                    "y":16},
                  "size":{
                    "width":70,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Page résultats in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"page_resultats.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u50.png",
              "mouseOver~":"images/home_new/u50_mouseOver.png"}},
{
            "id":"bf5e8c8074b04301a6d6f9c865f853f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":1050,
                "y":17},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9113f53a7cf41088451446e198b69d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":1050,
                    "y":17},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show Connection principale slide down 500 ms",
                        "objectsToFades":[{
                            "objectPath":["7959dfd8d1be4e2ea4de42bafcf6dadb"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideDown",
                                "duration":500,
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u52.png",
              "mouseOver~":"images/home_new/u52_mouseOver.png"}},
{
            "id":"7959dfd8d1be4e2ea4de42bafcf6dadb",
            "label":"Connection principale",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":810,
                "y":62},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide Connection principale slide up 500 ms",
                        "objectsToFades":[{
                            "objectPath":["7959dfd8d1be4e2ea4de42bafcf6dadb"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"slideUp",
                                "duration":500,
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"d74e4c75a08f40fc80ac76a598581ac3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"e19a9ea981a24b6a8cee2d7c2deea597",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0x91CCCCCC},
                      "size":{
                        "width":340,
                        "height":420},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ad3e720b759747dab604377dce0999ba",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0x91CCCCCC},
                          "size":{
                            "width":340,
                            "height":420},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home_new/u55.png"}},
{
                    "id":"befa936b561f47eb9a2f3bff9f347832",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":128},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d5334e95384f46c88e8ae7d3717b7544",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":128},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"d0c7581d8ea145518d3cef1c130ef6da",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":195},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"628852a4a3c34c668dfa713488cce041",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":195},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"a3287cfe06aa4125bf9c2a3b01387dd2",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"}},
                      "location":{
                        "x":40,
                        "y":264},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0265336a70e54693b29902276ac67714",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"}},
                          "location":{
                            "x":40,
                            "y":264},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"c77c9dc6b9974843b55c51bac7a11345",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":370},
                      "size":{
                        "width":340,
                        "height":10},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE9ECF0}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/home_new/u63_line.png"}},
{
                    "id":"8842143fb83b488a88dacb5ccb247748",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF33495F,
                        "opacity":1},
                      "lineSpacing":"18px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "paddingTop":"0",
                      "paddingBottom":"0",
                      "location":{
                        "x":64,
                        "y":360},
                      "size":{
                        "width":212,
                        "height":70},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2eebefd46e184db690aaeeebc512ba53",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF33495F,
                            "opacity":1},
                          "lineSpacing":"18px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "paddingTop":"0",
                          "paddingBottom":"0",
                          "location":{
                            "x":64,
                            "y":360},
                          "size":{
                            "width":212,
                            "height":70},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open S'inscrire in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"s_inscrire.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"852592aba57a4a91ab60165807ecf25c",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Light', 'Helvetica'",
                      "fontSize":"11px",
                      "fontWeight":"200",
                      "horizontalAlignment":"left",
                      "verticalAlignment":"top",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFB2BCC6,
                        "opacity":1},
                      "lineSpacing":"13px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "paddingTop":"0",
                      "paddingBottom":"0",
                      "location":{
                        "x":40,
                        "y":331},
                      "size":{
                        "width":260,
                        "height":38},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"558c0b51d80644a6b912e0a183d25752",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Light', 'Helvetica'",
                          "fontSize":"11px",
                          "fontWeight":"200",
                          "horizontalAlignment":"left",
                          "verticalAlignment":"top",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFB2BCC6,
                            "opacity":1},
                          "lineSpacing":"13px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "paddingTop":"0",
                          "paddingBottom":"0",
                          "location":{
                            "x":40,
                            "y":331},
                          "size":{
                            "width":260,
                            "height":38},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"32c10d9797634e5f99f21f6fe62b6d77",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":60},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8829368b94e547af8009f4a436c927d6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":60},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"a92708eaafbc42a892c386a59f5fc7b7",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontSize":"19px",
                      "location":{
                        "x":39,
                        "y":17},
                      "size":{
                        "width":266,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9ce8f206b51746d0a6fd83892576ff99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"19px",
                          "location":{
                            "x":39,
                            "y":17},
                          "size":{
                            "width":266,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"653ffc3c045246818d3fe290fadd1f0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":920,
                "y":16},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93d25658ae174b9a881e4e2715342ee8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":920,
                    "y":16},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open S'inscrire in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"s_inscrire.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u52.png",
              "mouseOver~":"images/home_new/u52_mouseOver.png"}},
{
            "id":"6dfe2a125a534ed9a0953735157c4b4a",
            "label":"Type de recherche",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":16},
              "size":{
                "width":70,
                "height":29}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "e6e937c3d80e40ed8c0ea3df7afbdaf4":{
      "scriptId":"u0"},
    "50424e4eb9d94997bf0f9bed24abb659":{
      "scriptId":"u1"},
    "ed5877d01e0a4ec4b04f12b703b32ad7":{
      "scriptId":"u2"},
    "a3e4782ee576413c81c6a2d2c2ec3f51":{
      "scriptId":"u3"},
    "95b584391fd8407ead95313fe7dfc007":{
      "scriptId":"u4"},
    "9c82215404d54d6aba904ff30a8c6e18":{
      "scriptId":"u5"},
    "b6dee754254c468ab869365be64c1f9a":{
      "scriptId":"u6",
      "43908beeeec1483d8cb2df8f5eaa2e43":{
        "scriptId":"u7"},
      "cde370c93f50410087af9b49ff4d8b76":{
        "scriptId":"u8"},
      "016b41db8d9547b6b3f8b61591c69297":{
        "scriptId":"u9"},
      "085d5ab409334489bb6c9f0828f02c66":{
        "scriptId":"u10"},
      "cc1a8431622b4110ad80a2438401755b":{
        "scriptId":"u11"},
      "03de8ddf973d4e64ad21713129ad31fd":{
        "scriptId":"u12"},
      "f54a7aeb5d5540a18f733d6bbc3b6f81":{
        "scriptId":"u13"},
      "1044fc2ff3784bcb91ae7c0270b5e1f8":{
        "scriptId":"u14"},
      "749bfa03b93a4b6b8eec17b252f0a62d":{
        "scriptId":"u15"}},
    "864208ae0ac24ee38e5cb7685b65625c":{
      "scriptId":"u16"},
    "af9f0701f5f04af68d566c066c18bd44":{
      "scriptId":"u17"},
    "ad9b1fbdd5b541719ff7df56153d5567":{
      "scriptId":"u18"},
    "d740f49946184314bfd4486bac5d1fc5":{
      "scriptId":"u19"},
    "6a2811cf29d844bc8b34c43e4ac55a53":{
      "scriptId":"u20"},
    "1a4aa3749c9145338657e94c8045c6f2":{
      "scriptId":"u21"},
    "f75e37dbff0f45209b8664d8974758bd":{
      "scriptId":"u22"},
    "9462db1c6b72461ea8e2be8388fdb032":{
      "scriptId":"u23"},
    "6e932f1a021149749afe5dce5bd35567":{
      "scriptId":"u24"},
    "9219675ae47a40b89c19637278f38975":{
      "scriptId":"u25"},
    "a379361c0ad6458c801c39f1c2043af9":{
      "scriptId":"u26"},
    "a66b6d03db974b9f830620391c6bb77a":{
      "scriptId":"u27"},
    "d6b85feadd494a5d937bde5712e197ef":{
      "scriptId":"u28"},
    "0269ec1e7961486d974f691ac3a65417":{
      "scriptId":"u29"},
    "1539e9e0165a477996c07bbcaadd03f0":{
      "scriptId":"u30"},
    "7998d360627b4c6f8cea4fea658d9fcd":{
      "scriptId":"u31"},
    "8fa622a4ae954a67a125d8dad0192f4d":{
      "scriptId":"u32"},
    "f1cab58d60f64573b89c8b9dd759aed8":{
      "scriptId":"u33"},
    "08c8b6d988054c028a58931e11a623ce":{
      "scriptId":"u34"},
    "80b6f556bb4f4de2b56ce32cf541956f":{
      "scriptId":"u35"},
    "475f4f8280584d00bf8fd5433984da98":{
      "scriptId":"u36",
      "9f139b2fe90d4dbead3502df555a174d":{
        "scriptId":"u37"},
      "67f79033071740f9b103569baf4c06df":{
        "scriptId":"u38"},
      "7f33424607814793b58b3d78593beb0f":{
        "scriptId":"u39"},
      "c5decc54edae450e8eb4d9306695250d":{
        "scriptId":"u40"},
      "2c3165e200cd4fe88e47b360a7918266":{
        "scriptId":"u41"},
      "ed083319a04d42abb62d4b13896cf78c":{
        "scriptId":"u42"},
      "a4d965d59f1449c79baf728c6e64e0bb":{
        "scriptId":"u43"},
      "75817ca8ea724b21bf3ce8b73acc6b62":{
        "scriptId":"u44"},
      "6e5acd9020a64e2dabc7477ac46888e2":{
        "scriptId":"u45"},
      "bf5e8c8074b04301a6d6f9c865f853f2":{
        "scriptId":"u46"},
      "c9113f53a7cf41088451446e198b69d4":{
        "scriptId":"u47"},
      "7959dfd8d1be4e2ea4de42bafcf6dadb":{
        "scriptId":"u48"},
      "e19a9ea981a24b6a8cee2d7c2deea597":{
        "scriptId":"u49"},
      "ad3e720b759747dab604377dce0999ba":{
        "scriptId":"u50"},
      "befa936b561f47eb9a2f3bff9f347832":{
        "scriptId":"u51"},
      "d5334e95384f46c88e8ae7d3717b7544":{
        "scriptId":"u52"},
      "d0c7581d8ea145518d3cef1c130ef6da":{
        "scriptId":"u53"},
      "628852a4a3c34c668dfa713488cce041":{
        "scriptId":"u54"},
      "a3287cfe06aa4125bf9c2a3b01387dd2":{
        "scriptId":"u55"},
      "0265336a70e54693b29902276ac67714":{
        "scriptId":"u56"},
      "c77c9dc6b9974843b55c51bac7a11345":{
        "scriptId":"u57"},
      "8842143fb83b488a88dacb5ccb247748":{
        "scriptId":"u58"},
      "2eebefd46e184db690aaeeebc512ba53":{
        "scriptId":"u59"},
      "852592aba57a4a91ab60165807ecf25c":{
        "scriptId":"u60"},
      "558c0b51d80644a6b912e0a183d25752":{
        "scriptId":"u61"},
      "32c10d9797634e5f99f21f6fe62b6d77":{
        "scriptId":"u62"},
      "8829368b94e547af8009f4a436c927d6":{
        "scriptId":"u63"},
      "a92708eaafbc42a892c386a59f5fc7b7":{
        "scriptId":"u64"},
      "9ce8f206b51746d0a6fd83892576ff99":{
        "scriptId":"u65"},
      "653ffc3c045246818d3fe290fadd1f0e":{
        "scriptId":"u66"},
      "93d25658ae174b9a881e4e2715342ee8":{
        "scriptId":"u67"},
      "6dfe2a125a534ed9a0953735157c4b4a":{
        "scriptId":"u68"}},
    "ac3cc2b6f8de438ab0aafafad5e93cbb":{
      "scriptId":"u69"},
    "cedaa5cf448a403fb6f95904d78f1244":{
      "scriptId":"u70"},
    "74711a60c8374d6a963005047d6848e9":{
      "scriptId":"u71"},
    "04186d64be524a2699cb784f99f7000e":{
      "scriptId":"u72"},
    "2288d8da4b7348828b9616573c98cfae":{
      "scriptId":"u73"},
    "aefbf27d8557497080bab8f48730f801":{
      "scriptId":"u74"},
    "0340e80b96034737a2493f50dda066d4":{
      "scriptId":"u75"},
    "f1d853d6d7a94df19b68b89320406782":{
      "scriptId":"u76"},
    "3a5542134515466e8f04a4b371b50a2e":{
      "scriptId":"u77"},
    "4a6e3f7c2a3841829622447930cbe9cb":{
      "scriptId":"u78"},
    "5991d44cf30d4ce39b9541b3a02cb95b":{
      "scriptId":"u79"},
    "3a4805a218624cd194bb10d94a0da8aa":{
      "scriptId":"u80"},
    "d6e5f971b0d245a481035b7a87b9c66d":{
      "scriptId":"u81"},
    "b74dbaaf6af34979bf2d7333faaf2ec6":{
      "scriptId":"u82"}}});