$axure.loadCurrentPage({
  "url":"home_new.html",
  "generationDate":new Date(1403793405806.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"00b113ae581549d197be2ffbb8ca11c5",
    "type":"Axure:Page",
    "name":"Home_new",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"10c1a6bcb66a40458a9124649804cdc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1280,
              "height":960}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df16ec0d1a9042f6a05c2940976bd76c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1280,
                  "height":960}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u0.jpg"}},
{
          "id":"e6a68d63324b4e4fa075c29ebe9a1d89",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb2e078b2f074854baea4c6b152f664f"},
{
          "id":"648a137ee4a2431a88c296adce9ad929",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":570,
              "y":330},
            "size":{
              "width":81,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bdaa3a50ea14d9c98afbfef282d850d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":330},
                "size":{
                  "width":81,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"7985cb4b81134056a57ca5bbc7c92a16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":230,
              "y":335},
            "size":{
              "width":60,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f23504ca3024b20b17cd59fbbbdb5ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":335},
                "size":{
                  "width":60,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"fc7e400590bf46f7b5c702f42a2c4cdd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":689,
              "y":470},
            "size":{
              "width":55,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8495b0648c664a88a812eb85e87e533b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":689,
                  "y":470},
                "size":{
                  "width":55,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"a361bc9fcbfd4f4cbaec9741460b1748",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":744,
              "y":210},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b22bdfa8174e569e1e48e4c0180efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":744,
                  "y":210},
                "size":{
                  "width":66,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"c77e1ff612b04142ad5af847c890f287",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":169,
              "y":408},
            "size":{
              "width":71,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e348a3f23d0b43c0a58b62797b056776",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":169,
                  "y":408},
                "size":{
                  "width":71,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/u12.png"}},
{
          "id":"77d1daf54184409a930fc6b13a80cde2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1064,
              "y":463},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03aa7c076f3341959c2233f99f4f7655",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1064,
                  "y":463},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"2d5f3cde88734e74bb5fc00b88eaa22d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1064,
              "y":398},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e2a613a982b41a2bc2e146342853f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1064,
                  "y":398},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"d341d3bdd2354ca1a6bd764f33775b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1064,
              "y":333},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d8eec2eee5f4783b4bb099337d10442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1064,
                  "y":333},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"f4965f9239ea4fffa4ecb9cf59a28e19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1064,
              "y":267},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3ca4971990421e896a15cfc96cc1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1064,
                  "y":267},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"8a560ed5dabd4a7eb468e6edf5031234",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":1064,
              "y":202},
            "size":{
              "width":86,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36da7177c007470d8410cd3f3d156e3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF515151}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":1064,
                  "y":202},
                "size":{
                  "width":86,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u22.png",
            "mouseOver~":"images/home_new/u22_mouseOver.png"}},
{
          "id":"2f7dbb5eb73d4d6da021a70095224e35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":1280,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0757cd8d7441a9bb9ee8499a7aa3dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":1280,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home_new/u32.png"}},
{
          "id":"1bf4c600eec44e4f8ee6756353f7a7d3",
          "label":"Button.Simple",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":430,
              "y":362},
            "size":{
              "width":110,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9689a9255a30488e99179f92ea76c91a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9}]}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF363636,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":430,
                  "y":362},
                "size":{
                  "width":110,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home_step1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home_step1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/button_simple_u34.png",
            "mouseOver~":"images/home_new/button_simple_u34_mouseOver.png",
            "mouseDown~":"images/home_new/button_simple_u34_mouseDown.png"}},
{
          "id":"7aaffc95a38a4214bdf7fb78db492f93",
          "label":"Button.Simple",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFC9C9C9},
{
                      "color":0xFFC9C9C9}]}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":580,
              "y":365},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7310b191d7242c2ac162b21ba82bcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFE4E4E4},
{
                          "color":0xFFC9C9C9},
{
                          "color":0xFFC9C9C9}]}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF363636,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":580,
                  "y":365},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home_new/button_simple_u36.png",
            "mouseOver~":"images/home_new/button_simple_u36_mouseOver.png",
            "mouseDown~":"images/home_new/button_simple_u36_mouseDown.png"}},
{
          "id":"bb23059b34354e6eacd3df2c9a7f8f97",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":120},
            "size":{
              "width":252,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca46d1abd7e478995cc4339476d1b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":120},
                "size":{
                  "width":252,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0030a28937e64c47a4cb01afb34478cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":280,
              "y":192},
            "size":{
              "width":490,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4fa268d1074668a17f2d785b8b6f88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":280,
                  "y":192},
                "size":{
                  "width":490,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9de0e81967b84630aa1a569588e74bea",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"08c5e6d3e5f54a259a8534ebaa863b4a"}]}},
  "masters":{
    "bb2e078b2f074854baea4c6b152f664f":{
      "packageId":"bb2e078b2f074854baea4c6b152f664f",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"43908beeeec1483d8cb2df8f5eaa2e43",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":920},
              "size":{
                "width":1280,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cde370c93f50410087af9b49ff4d8b76",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":920},
                  "size":{
                    "width":1280,
                    "height":40}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"016b41db8d9547b6b3f8b61591c69297",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"085d5ab409334489bb6c9f0828f02c66",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true},
{
                    "id":"cc1a8431622b4110ad80a2438401755b",
                    "label":"",
                    "type":"hyperlink",
                    "styleType":"hyperlink",
                    "visible":true,
                    "style":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Link in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true}]}],
            "images":{
              "normal~":"images/home_new/u3.png"}},
{
            "id":"03de8ddf973d4e64ad21713129ad31fd",
            "label":"facebook icone",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":880,
                "y":924},
              "size":{
                "width":30,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f54a7aeb5d5540a18f733d6bbc3b6f81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":880,
                    "y":924},
                  "size":{
                    "width":30,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open https://www.facebook.com/warpathcommunity?ref=hl in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"https://www.facebook.com/warpathcommunity?ref=hl",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/facebook_icone_u8.png"}},
{
            "id":"1044fc2ff3784bcb91ae7c0270b5e1f8",
            "label":"instagram icon",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":950,
                "y":926},
              "size":{
                "width":30,
                "height":28}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"749bfa03b93a4b6b8eec17b252f0a62d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":950,
                    "y":926},
                  "size":{
                    "width":30,
                    "height":28}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open http://instagram.com/warpathcommunity in New Window/Tab",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://instagram.com/warpathcommunity",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/instagram_icon_u10.png"}}]}},
    "08c5e6d3e5f54a259a8534ebaa863b4a":{
      "packageId":"08c5e6d3e5f54a259a8534ebaa863b4a",
      "type":"Axure:Master",
      "name":"Header",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9f139b2fe90d4dbead3502df555a174d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF797979},
              "size":{
                "width":1280,
                "height":62}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"67f79033071740f9b103569baf4c06df",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF797979},
                  "size":{
                    "width":1280,
                    "height":62}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home_new/u43.png"}},
{
            "id":"7f33424607814793b58b3d78593beb0f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":0},
              "size":{
                "width":130,
                "height":120}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5decc54edae450e8eb4d9306695250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":80,
                    "y":0},
                  "size":{
                    "width":130,
                    "height":120}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u45.png"}},
{
            "id":"2c3165e200cd4fe88e47b360a7918266",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":91,
                "y":5},
              "size":{
                "width":108,
                "height":108}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ed083319a04d42abb62d4b13896cf78c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":91,
                    "y":5},
                  "size":{
                    "width":108,
                    "height":108}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u47.png"}},
{
            "id":"a4d965d59f1449c79baf728c6e64e0bb",
            "label":"search bar",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":258,
                "y":16},
              "size":{
                "width":492,
                "height":29}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onTextChange":{
                "description":"OnTextChange",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"Set text on search bar equal to &quot;&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetWidgetFormText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["a4d965d59f1449c79baf728c6e64e0bb"]},
{
                                  "exprType":"stringLiteral",
                                  "value":"",
                                  "stos":[]}]}]}}]}]}}},
{
            "id":"75817ca8ea724b21bf3ce8b73acc6b62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "fill":{
                "fillType":"solid",
                "color":0xFF434343},
              "location":{
                "x":820,
                "y":16},
              "size":{
                "width":70,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e5acd9020a64e2dabc7477ac46888e2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF434343},
                  "location":{
                    "x":820,
                    "y":16},
                  "size":{
                    "width":70,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Page résultats in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"page_resultats.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u50.png",
              "mouseOver~":"images/home_new/u50_mouseOver.png"}},
{
            "id":"bf5e8c8074b04301a6d6f9c865f853f2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":1050,
                "y":17},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c9113f53a7cf41088451446e198b69d4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":1050,
                    "y":17},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show Connection principale slide down 500 ms",
                        "objectsToFades":[{
                            "objectPath":["7959dfd8d1be4e2ea4de42bafcf6dadb"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "easing":"slideDown",
                                "duration":500,
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u52.png",
              "mouseOver~":"images/home_new/u52_mouseOver.png"}},
{
            "id":"7959dfd8d1be4e2ea4de42bafcf6dadb",
            "label":"Connection principale",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":810,
                "y":62},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Hide Connection principale slide up 500 ms",
                        "objectsToFades":[{
                            "objectPath":["7959dfd8d1be4e2ea4de42bafcf6dadb"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "easing":"slideUp",
                                "duration":500,
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"d74e4c75a08f40fc80ac76a598581ac3",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"e19a9ea981a24b6a8cee2d7c2deea597",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0x91CCCCCC},
                      "size":{
                        "width":340,
                        "height":420},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ad3e720b759747dab604377dce0999ba",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0x91CCCCCC},
                          "size":{
                            "width":340,
                            "height":420},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home_new/u55.png"}},
{
                    "id":"befa936b561f47eb9a2f3bff9f347832",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":128},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d5334e95384f46c88e8ae7d3717b7544",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":128},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"d0c7581d8ea145518d3cef1c130ef6da",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":195},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"628852a4a3c34c668dfa713488cce041",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":195},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"a3287cfe06aa4125bf9c2a3b01387dd2",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"}},
                      "location":{
                        "x":40,
                        "y":264},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0265336a70e54693b29902276ac67714",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"}},
                          "location":{
                            "x":40,
                            "y":264},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"c77c9dc6b9974843b55c51bac7a11345",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"horizontalLine",
                    "styleType":"horizontalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":0,
                        "y":370},
                      "size":{
                        "width":340,
                        "height":10},
                      "borderWidth":"2",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE9ECF0}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/home_new/u63_line.png"}},
{
                    "id":"8842143fb83b488a88dacb5ccb247748",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"14px",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF33495F,
                        "opacity":1},
                      "lineSpacing":"18px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "paddingTop":"0",
                      "paddingBottom":"0",
                      "location":{
                        "x":64,
                        "y":360},
                      "size":{
                        "width":212,
                        "height":70},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2eebefd46e184db690aaeeebc512ba53",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"14px",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF33495F,
                            "opacity":1},
                          "lineSpacing":"18px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "paddingTop":"0",
                          "paddingBottom":"0",
                          "location":{
                            "x":64,
                            "y":360},
                          "size":{
                            "width":212,
                            "height":70},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open S'inscrire in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"s_inscrire.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"852592aba57a4a91ab60165807ecf25c",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica Light', 'Helvetica'",
                      "fontSize":"11px",
                      "fontWeight":"200",
                      "horizontalAlignment":"left",
                      "verticalAlignment":"top",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFB2BCC6,
                        "opacity":1},
                      "lineSpacing":"13px",
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "paddingTop":"0",
                      "paddingBottom":"0",
                      "location":{
                        "x":40,
                        "y":331},
                      "size":{
                        "width":260,
                        "height":38},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"558c0b51d80644a6b912e0a183d25752",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica Light', 'Helvetica'",
                          "fontSize":"11px",
                          "fontWeight":"200",
                          "horizontalAlignment":"left",
                          "verticalAlignment":"top",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFB2BCC6,
                            "opacity":1},
                          "lineSpacing":"13px",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "paddingTop":"0",
                          "paddingBottom":"0",
                          "location":{
                            "x":40,
                            "y":331},
                          "size":{
                            "width":260,
                            "height":38},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"32c10d9797634e5f99f21f6fe62b6d77",
                    "label":"follow_text-2",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'Helvetica'",
                      "fontSize":"18px",
                      "fontWeight":"400",
                      "horizontalAlignment":"left",
                      "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                      "lineSpacing":"16px",
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFF2F2F2,
                            "opacity":1},
                          "opacity":"0.8"},
                        "mouseDown":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                        "selected":{
                          "baseStyle":"627587b6038d43cca051c114ac41ad32",
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF21CA6B}}},
                      "location":{
                        "x":40,
                        "y":60},
                      "size":{
                        "width":260,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8829368b94e547af8009f4a436c927d6",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Helvetica'",
                          "fontSize":"18px",
                          "fontWeight":"400",
                          "horizontalAlignment":"left",
                          "baseStyle":"a41a158a99a841118d561e8ba97264dd",
                          "lineSpacing":"16px",
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2,
                                "opacity":1},
                              "opacity":"0.8"},
                            "mouseDown":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32"},
                            "selected":{
                              "baseStyle":"627587b6038d43cca051c114ac41ad32",
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF21CA6B}}},
                          "location":{
                            "x":40,
                            "y":60},
                          "size":{
                            "width":260,
                            "height":50}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Home log in in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"home_log_in.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home_new/follow_text-2_u57.png",
                      "selected~":"images/home_new/follow_text-2_u57_selected.png",
                      "mouseOver~":"images/home_new/follow_text-2_u57.png",
                      "mouseDown~":"images/home_new/follow_text-2_u57.png"}},
{
                    "id":"a92708eaafbc42a892c386a59f5fc7b7",
                    "label":"",
                    "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontSize":"19px",
                      "location":{
                        "x":39,
                        "y":17},
                      "size":{
                        "width":266,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9ce8f206b51746d0a6fd83892576ff99",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"7959dfd8d1be4e2ea4de42bafcf6dadb",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"19px",
                          "location":{
                            "x":39,
                            "y":17},
                          "size":{
                            "width":266,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]},
{
            "id":"653ffc3c045246818d3fe290fadd1f0e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF3366}}},
              "location":{
                "x":920,
                "y":16},
              "size":{
                "width":100,
                "height":29}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"93d25658ae174b9a881e4e2715342ee8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFF3366}}},
                  "location":{
                    "x":920,
                    "y":16},
                  "size":{
                    "width":100,
                    "height":29}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open S'inscrire in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"s_inscrire.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home_new/u52.png",
              "mouseOver~":"images/home_new/u52_mouseOver.png"}},
{
            "id":"6dfe2a125a534ed9a0953735157c4b4a",
            "label":"Type de recherche",
            "type":"comboBox",
            "styleType":"comboBox",
            "visible":true,
            "style":{
              "location":{
                "x":750,
                "y":16},
              "size":{
                "width":70,
                "height":29}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "10c1a6bcb66a40458a9124649804cdc7":{
      "scriptId":"u0"},
    "df16ec0d1a9042f6a05c2940976bd76c":{
      "scriptId":"u1"},
    "e6a68d63324b4e4fa075c29ebe9a1d89":{
      "scriptId":"u2",
      "43908beeeec1483d8cb2df8f5eaa2e43":{
        "scriptId":"u3"},
      "cde370c93f50410087af9b49ff4d8b76":{
        "scriptId":"u4"},
      "016b41db8d9547b6b3f8b61591c69297":{
        "scriptId":"u5"},
      "085d5ab409334489bb6c9f0828f02c66":{
        "scriptId":"u6"},
      "cc1a8431622b4110ad80a2438401755b":{
        "scriptId":"u7"},
      "03de8ddf973d4e64ad21713129ad31fd":{
        "scriptId":"u8"},
      "f54a7aeb5d5540a18f733d6bbc3b6f81":{
        "scriptId":"u9"},
      "1044fc2ff3784bcb91ae7c0270b5e1f8":{
        "scriptId":"u10"},
      "749bfa03b93a4b6b8eec17b252f0a62d":{
        "scriptId":"u11"}},
    "648a137ee4a2431a88c296adce9ad929":{
      "scriptId":"u12"},
    "3bdaa3a50ea14d9c98afbfef282d850d":{
      "scriptId":"u13"},
    "7985cb4b81134056a57ca5bbc7c92a16":{
      "scriptId":"u14"},
    "0f23504ca3024b20b17cd59fbbbdb5ed":{
      "scriptId":"u15"},
    "fc7e400590bf46f7b5c702f42a2c4cdd":{
      "scriptId":"u16"},
    "8495b0648c664a88a812eb85e87e533b":{
      "scriptId":"u17"},
    "a361bc9fcbfd4f4cbaec9741460b1748":{
      "scriptId":"u18"},
    "d5b22bdfa8174e569e1e48e4c0180efa":{
      "scriptId":"u19"},
    "c77e1ff612b04142ad5af847c890f287":{
      "scriptId":"u20"},
    "e348a3f23d0b43c0a58b62797b056776":{
      "scriptId":"u21"},
    "77d1daf54184409a930fc6b13a80cde2":{
      "scriptId":"u22"},
    "03aa7c076f3341959c2233f99f4f7655":{
      "scriptId":"u23"},
    "2d5f3cde88734e74bb5fc00b88eaa22d":{
      "scriptId":"u24"},
    "7e2a613a982b41a2bc2e146342853f62":{
      "scriptId":"u25"},
    "d341d3bdd2354ca1a6bd764f33775b48":{
      "scriptId":"u26"},
    "4d8eec2eee5f4783b4bb099337d10442":{
      "scriptId":"u27"},
    "f4965f9239ea4fffa4ecb9cf59a28e19":{
      "scriptId":"u28"},
    "5f3ca4971990421e896a15cfc96cc1fe":{
      "scriptId":"u29"},
    "8a560ed5dabd4a7eb468e6edf5031234":{
      "scriptId":"u30"},
    "36da7177c007470d8410cd3f3d156e3a":{
      "scriptId":"u31"},
    "2f7dbb5eb73d4d6da021a70095224e35":{
      "scriptId":"u32"},
    "ff0757cd8d7441a9bb9ee8499a7aa3dc":{
      "scriptId":"u33"},
    "1bf4c600eec44e4f8ee6756353f7a7d3":{
      "scriptId":"u34"},
    "9689a9255a30488e99179f92ea76c91a":{
      "scriptId":"u35"},
    "7aaffc95a38a4214bdf7fb78db492f93":{
      "scriptId":"u36"},
    "b7310b191d7242c2ac162b21ba82bcfb":{
      "scriptId":"u37"},
    "bb23059b34354e6eacd3df2c9a7f8f97":{
      "scriptId":"u38"},
    "bca46d1abd7e478995cc4339476d1b90":{
      "scriptId":"u39"},
    "0030a28937e64c47a4cb01afb34478cd":{
      "scriptId":"u40"},
    "4e4fa268d1074668a17f2d785b8b6f88":{
      "scriptId":"u41"},
    "9de0e81967b84630aa1a569588e74bea":{
      "scriptId":"u42",
      "9f139b2fe90d4dbead3502df555a174d":{
        "scriptId":"u43"},
      "67f79033071740f9b103569baf4c06df":{
        "scriptId":"u44"},
      "7f33424607814793b58b3d78593beb0f":{
        "scriptId":"u45"},
      "c5decc54edae450e8eb4d9306695250d":{
        "scriptId":"u46"},
      "2c3165e200cd4fe88e47b360a7918266":{
        "scriptId":"u47"},
      "ed083319a04d42abb62d4b13896cf78c":{
        "scriptId":"u48"},
      "a4d965d59f1449c79baf728c6e64e0bb":{
        "scriptId":"u49"},
      "75817ca8ea724b21bf3ce8b73acc6b62":{
        "scriptId":"u50"},
      "6e5acd9020a64e2dabc7477ac46888e2":{
        "scriptId":"u51"},
      "bf5e8c8074b04301a6d6f9c865f853f2":{
        "scriptId":"u52"},
      "c9113f53a7cf41088451446e198b69d4":{
        "scriptId":"u53"},
      "7959dfd8d1be4e2ea4de42bafcf6dadb":{
        "scriptId":"u54"},
      "e19a9ea981a24b6a8cee2d7c2deea597":{
        "scriptId":"u55"},
      "ad3e720b759747dab604377dce0999ba":{
        "scriptId":"u56"},
      "befa936b561f47eb9a2f3bff9f347832":{
        "scriptId":"u57"},
      "d5334e95384f46c88e8ae7d3717b7544":{
        "scriptId":"u58"},
      "d0c7581d8ea145518d3cef1c130ef6da":{
        "scriptId":"u59"},
      "628852a4a3c34c668dfa713488cce041":{
        "scriptId":"u60"},
      "a3287cfe06aa4125bf9c2a3b01387dd2":{
        "scriptId":"u61"},
      "0265336a70e54693b29902276ac67714":{
        "scriptId":"u62"},
      "c77c9dc6b9974843b55c51bac7a11345":{
        "scriptId":"u63"},
      "8842143fb83b488a88dacb5ccb247748":{
        "scriptId":"u64"},
      "2eebefd46e184db690aaeeebc512ba53":{
        "scriptId":"u65"},
      "852592aba57a4a91ab60165807ecf25c":{
        "scriptId":"u66"},
      "558c0b51d80644a6b912e0a183d25752":{
        "scriptId":"u67"},
      "32c10d9797634e5f99f21f6fe62b6d77":{
        "scriptId":"u68"},
      "8829368b94e547af8009f4a436c927d6":{
        "scriptId":"u69"},
      "a92708eaafbc42a892c386a59f5fc7b7":{
        "scriptId":"u70"},
      "9ce8f206b51746d0a6fd83892576ff99":{
        "scriptId":"u71"},
      "653ffc3c045246818d3fe290fadd1f0e":{
        "scriptId":"u72"},
      "93d25658ae174b9a881e4e2715342ee8":{
        "scriptId":"u73"},
      "6dfe2a125a534ed9a0953735157c4b4a":{
        "scriptId":"u74"}}}});